apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/publicEndpoints: '[{"addresses":["34.229.154.130"],"port":32162,"protocol":"TCP","serviceName":"default:tomcat","allNodes":true}]'
  creationTimestamp: "2020-03-15T23:46:07Z"
  generation: 2
  labels:
    run: tomcat
  name: tomcat
  namespace: default
  resourceVersion: "2117"
  selfLink: /apis/apps/v1/namespaces/default/deployments/tomcat
  uid: 6e8d329a-bd9e-4901-a1c8-20e6b063fe65
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: tomcat
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: tomcat
    spec:
      containers:
      - image: haramrit09k/docker-test:latest
        imagePullPolicy: Always
        name: tomcat
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-15T23:46:43Z"
    lastUpdateTime: "2020-03-15T23:46:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-03-15T23:46:27Z"
    lastUpdateTime: "2020-03-15T23:46:43Z"
    message: ReplicaSet "tomcat-5dc665d685" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
